### ISSUE TITLE
alg-HPのthemes/hugo-theme-stack/ がcloneされない

### ISSUE THREAD

**Issue by mugicha9** [RICORA/alg-HP#105]
`git clone --recursive git@github.com:RICORA/alg-HP.git`
を実行すると
`Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:CaiJimmy/hugo-theme-stack.git' into submodule path 'C:/workspace/alg-HP/themes/hugo-theme-stack' failed`
のようなエラーが出て、正常にcloneできません

githubにsshの公開鍵を登録してssh -T git@github.comで接続を確認できています。

**Comment by phnyo** [comment]
git clone --recursive でcloneしてみてください

**Comment by mugicha9** [comment]
git clone --recursive git@github.com:RICORA/alg-HP.git
git clone --recursive https://github.com/RICORA/alg-HP.git
のように --recursiveをつけても上記のエラーが出ています

**Comment by phnyo** [comment]
このサークルの別のリポジトリとかはcloneできますか？ちゃんとコメント読んでなくて申し訳ない

**Comment by mugicha9** [comment]
sshでRICORA/tuc-ricora.comとsandboxはcloneできました

**Comment by mugicha9** [comment]
今git bashから実行したらcloneできました
推測ですが、Powershellやcmdからsshでgitを使うと、alg-HPのcloneに対するsshの認証は行われる(パスコードが求められる)が、submoduleのcloneに対してsshの認証が行われないために正常にcloneできないのだと思います。
git bashからcloneした際はhugo-theme-stackのsubmoduleのcloneに対して2回目のパスコードが求められたので、きっとそういうことだと()
とりあえずの解決策は git bashでclone です

**Comment by phnyo** [comment]
り、了解です...
