### ISSUE TITLE
新歓用ページのさくせい

### ISSUE THREAD

**Issue by phnyo** [RICORA/alg-HP#43]
スケジュールとか全部ひっくるめて案内できるページがあればいいかも

**Comment by Shinonome517** [comment]
半分書き終えました

今日中にpull req 出します

**Comment by phnyo** [comment]
🙆🙆🙆

**Comment by phnyo** [comment]
画面が小さい端末に対してbootstrapのカードみたいな感じにして可読性を上げたい

**Comment by phnyo** [comment]
done on #60
