### ISSUE TITLE
リンクを本番用に差し替え

### ISSUE THREAD

**Issue by 7319064** [RICORA/alg-HP#54]
https://alg.tus-ricora.com/link/

**Comment by phnyo** [comment]
#62

**Comment by Shinonome517** [comment]
リンクにTwitterとGitHubをついかしたほうが良いのではないでしょうか？
左上の小さいアイコンだけだと、見つけづらいです

**Comment by phnyo** [comment]
yml編集するだけなんで対応お願いします🙇

**Comment by Shinonome517** [comment]
🙆🙆🙆
