### ISSUE TITLE
リンクの反応範囲の拡張

### ISSUE THREAD

**Issue by Shinonome517** [RICORA/alg-HP#74]
左のリストをクリックするときに、文字の上しか反応しないのが気になる。

CSSでaタグをブロック要素にすれば、クリックしやすくなるのではないか？

**Comment by phnyo** [comment]
環境を明示していただけると助かります！🙇🙇🙇

**Comment by Shinonome517** [comment]
> 環境を明示していただけると助かります！🙇🙇🙇

MacBookのGoogleChromeでです
次回から明示します
