### ISSUE TITLE
記事の内容を更新したときに、更新日時を反映させたい。

### ISSUE THREAD

**Issue by Shinonome517** [RICORA/alg-HP#92]
## 概略

記事の更新をしたときに、更新日時を反映させたいです。

![image](https://user-images.githubusercontent.com/66119716/162872325-4de6118e-e13b-4726-b249-ef96cf85fcb8.png)

## 詳細

GMT+9hの表記で、上記の画像部分を更新日時に変更してもよいでしょうか？

質問の意図としては

* 技術的な側面として、手で変えて問題ないか？
* これからのブログ運営ルールとして、更新日時に手動で変更するようにしてもよいか？

の二つを含んでいます。

**Comment by 7319064** [comment]
更新日時は`lastmod`で記述してください

https://gohugo.io/variables/page/

**Comment by phnyo** [comment]
さっきmergeしたPRでは下に更新日時が表示されるようになっています。
絵文字の下に日時を表示する場合は、layout/particle/article/components/details.html を編集すれば可能なはずですが、ちょっと上の記述だとどのような感じに変更すればいいのかわからないので具体的にきじゅつしていただけれると対応できると思います

**Comment by phnyo** [comment]
https://github.com/RICORA/alg-HP/tree/feature/show-lastmod こういうこと？

**Comment by Shinonome517** [comment]
feature/show-lastmodを確認しました。

記事の上部に更新日時が見られるようになってて最高です。

PRお願いします。
